repos:
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
    - id: black
      language_version: python3.11

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      additional_dependencies: [toml]

- repo: local
  hooks:
    - id: uv-pip-compile
      name: Generate requirements.txt with uv
      language: system
      entry: uv pip compile pyproject.toml -o requirements.txt
      files: ^pyproject\.toml$
      pass_filenames: false
      always_run: true