repos:
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
    - id: black
      language_version: python3.11
      files: ^.*\.py$

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      additional_dependencies: [toml]
      files: ^.*\.py$

- repo: local
  hooks:
    - id: export-requirements
      name: Export requirements.txt
      entry: bash -c 'uv pip compile pyproject.toml -o requirements.txt'
      language: system
      files: ^pyproject\.toml$
      pass_filenames: false
